# Makefile.deps created Sun May 12 04:41:00 PDT 2019 by make
astree.o: astree.cpp astree.h auxlib.h string_set.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h yyparse.h
string_set.o: string_set.cpp auxlib.h string_set.h
auxlib.o: auxlib.cpp auxlib.h
oc.o: oc.cpp string_set.h astree.h auxlib.h lyutils.h yyparse.h
yylex.o: yylex.cpp lyutils.h astree.h auxlib.h yyparse.h
yyparse.o: yyparse.cpp astree.h auxlib.h lyutils.h yyparse.h
